"""empty message

Revision ID: 56eb0d95e5bb
Revises: 83ddc97f6a5b
Create Date: 2026-01-18 10:02:22.586698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eb0d95e5bb'
down_revision = '83ddc97f6a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('especie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('especie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
